s = input("Digite algo: ")
print("O tipo primtivo desse valor é", type(s))
print("Só tem espaços?", s.isspace())
print("É um número?", s.isnumeric())
print("É alfabético?", s.isalpha())
print("É alfanumérico?", s.isalnum())
print("Está em maiúsculas?", s.isupper())
print("Está em minúsculas?", s.isupper())
print("Está captalizada?", s.istitle())
